name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: registry-intl.ap-southeast-5.aliyuncs.com
          username: "${{ secrets.DOCKER_LOGIN_USER }}"
          password: "${{ secrets.DOCKER_LOGIN_PASS }}"
      - name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t registry-intl.ap-southeast-5.aliyuncs.com/devops_pouk/nest_test:latest .
          docker push registry-intl.ap-southeast-5.aliyuncs.com/devops_pouk/nest_test:latest
        
#       - uses: actions/checkout@v3
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        
#       - name: Login to Alibaba
#         uses: docker/login-action@v2
#         with:
#           registry: registry-intl.ap-southeast-5.aliyuncs.com
#           username: ${{ secrets.DOCKER_LOGIN_USER }}
#           password: ${{ secrets.DOCKER_LOGIN_PASS }}
        
#       - name: push to alibaba
#         run:
#           docker push registry-intl.ap-southeast-5.aliyuncs.com/devops_pouk/nest_test:latest
      
      # - uses: aliyun/acr-login@v1
      #   with:
      #     login-server: '<login server>' # example: https://my-test-registry.cn-hangzhou.cr.aliyuncs.com
      #     region-id: '<region id>' # example: cn-hangzhou
      #     access-key-id: '<access key id>'
      #     access-key-secret: '<access key secret>'
      #     instance-id: '<registry instance id>'
      
      # - name: Build and push image
      #   env:
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t registry.cn-hangzhou.aliyuncs.com/myrepo/demo:$IMAGE_TAG .
      #     docker push registry.cn-hangzhou.aliyuncs.com/myrepo/demo:$IMAGE_TAG

      # - uses: aliyun/ack-set-context@v1
      # - name: Connect alibaba ACK
      #   with:

      #     access-key-id: ${{ secrets.ACCESS_KEY }}
      #     access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      #     cluster-id: ${{ secret.ACK_CLUSTER_ID }}
