name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v3
      
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server:  https://registry-intl.ap-southeast-5.aliyuncs.com
          username: "${{ secrets.DOCKER_LOGIN_USER }}"
          password: "${{ secrets.DOCKER_LOGIN_PASS }}"
      - name: Build and push image
        run: |
          docker build -t registry-intl.ap-southeast-5.aliyuncs.com/devops_pouk/nest_test:latest  .
          docker push registry-intl.ap-southeast-5.aliyuncs.com/devops_pouk/nest_test:latest

      - name: SSH to server
#         uses: fifsky/ssh-action@master
#         with:
#           command: |
#             docker login --username=${{ secrets.DOCKER_LOGIN_USER }} --password=${{ secrets.DOCKER_LOGIN_PASS }} registry-intl.ap-southeast-5.aliyuncs.com
#             docker pull registry-intl.ap-southeast-5.aliyuncs.com/devops_pouk/nest_test:latest
#             docker run -d  --name nest_test -p 3000:3000 registry-intl.ap-southeast-5.aliyuncs.com/devops_pouk/nest_test:latest
#           host: ${{ secrets.SSH_HOST }}
#           user: root
#           key: ${{ secrets.SSH_KEY_RSA }}
          
          
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY_ED25519 }}
          port: ${{ secrets.SSH_PORT }}
          script:  |
            docker login --username=${{ secrets.DOCKER_LOGIN_USER }} --password=${{ secrets.DOCKER_LOGIN_PASS }} registry-intl.ap-southeast-5.aliyuncs.com
            docker pull registry-intl.ap-southeast-5.aliyuncs.com/devops_pouk/nest_test:latest
            docker stop --name nest_test
            docker rm -f nest_test &>/dev/null
            docker run -d  --name nest_test -p 3000:3000 registry-intl.ap-southeast-5.aliyuncs.com/devops_pouk/nest_test:latest
